-- Create SQL login for KPMIS
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'KPMIS')
BEGIN
    CREATE LOGIN [KPMIS] WITH PASSWORD = N'KPM6admin_', DEFAULT_DATABASE = [7E2088], CHECK_POLICY = OFF;
END
GO

USE [7E2088];
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'KPMIS')
BEGIN
    CREATE USER [KPMIS] FOR LOGIN [KPMIS];
    ALTER ROLE [db_owner] ADD MEMBER [KPMIS];
END
GO

USE [7E2088_Annex];
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'KPMIS')
BEGIN
    CREATE USER [KPMIS] FOR LOGIN [KPMIS];
    ALTER ROLE [db_owner] ADD MEMBER [KPMIS];
END
GO
